### ISSUE TITLE
Non-whitespace before first tag

### ISSUE THREAD

**Issue by twhiteheadzm** [spmeesseman/vscode-taskexplorer#135]
v2.0.1
Loads forever and shows in dev tools:
`mainThreadExtensionService.ts:60 Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: u
	at error (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\sax\lib\sax.js:651:10)
	at strictFail (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\sax\lib\sax.js:677:7)
	at beginWhiteSpace (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\sax\lib\sax.js:951:7)
	at SAXParser.write (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\sax\lib\sax.js:1006:11)
	at Parser.exports.Parser.Parser.parseString (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\xml2js\lib\parser.js:323:31)
	at Parser.parseString (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\xml2js\lib\parser.js:5:59)
	at c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\xml2js\lib\parser.js:338:24
	at new Promise (<anonymous>)
	at Parser.exports.Parser.Parser.parseStringPromise (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\xml2js\lib\parser.js:336:14)
	at Parser.parseStringPromise (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\xml2js\lib\parser.js:5:59)
	at Object.exports.parseStringPromise (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\node_modules\xml2js\lib\parser.js:378:19)
	at AntTaskProvider.<anonymous> (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\out\taskProviderAnt.js:221:41)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Timothy\.vscode\extensions\spmeesseman.vscode-taskexplorer-2.0.1\out\taskProviderAnt.js:5:58)`

**Comment by spmeesseman** [comment]
@twhiteheadzm - i got this one fixed i think, please try 2.0.2, can u confirm fixed or not?

**Comment by twhiteheadzm** [comment]
Yes v2.0.2 fixed it.
